metadata:
  name: expops-test-project
  description: A new component-authored pipeline for expops-test.
  version: 1.0.0
scripts: {}
environment:
  sklearn-env:
    venv:
      - requirements.txt
reproducibility:
  random_seed: 42
data:
  path: data/train.csv
experiment:
  cache:
    backend:
      type: local
  pipeline:
    process_adjlist: |-
      data_source train_test_split
      train_test_split logisticregression_fit_predict
    processes:
      - name: data_source
        type: process
        component: sklearn.csv_to_xy
        parameters:
          label_column: label
      - name: train_test_split
        type: process
        component: sklearn.train_test_split
        parameters:
          test_size: 0.2
          random_state: 42
      - name: logisticregression_fit_predict
        type: process
        component: sklearn.LogisticRegression.fit_predict
        parameters:
          max_iter: 200
        input_transform:
          X: X_train
          y: y_train